console.log(JSON.stringify(10))
console.log(JSON.stringify('JavaScript'))
console.log(JSON.stringify(true))
console.log(JSON.stringify({ name: 'Selfs', paradigm: 'OO' }))
console.log(JSON.stringify([1, 2, 3, 4, 5, 6, 7, 8, 9]))
console.log(JSON.stringify(null))